### ISSUE TITLE
Support for closed track releases

### ISSUE THREAD

**Issue by slavikdenis** [leanmotherfuckers/react-native-check-version#5]
Hello.

Any ideas, is there would be a possibility to get latest version of an android app from google play, which is closed track (alpha) release only?

Basically, it's accessible only by people granted based on email.

So maybe if there would be a configuration option like email/password OR some google API token (no idea how these works) it could be accessed?

Thanks

**Comment by tschoffelen** [comment]
It is probably possible to do something like this, but not with the way we currently get version numbers, since we basically just scrape the public Google Play app page and look for the version number.

There might indeed be a way to get it via the Google Play API, but it might be easier in that case to specify your own endpoint and create a script yourself to do so. I'm not planning to add that to this repo myself any time soon, but will of course welcome pull requests for the server component as well!

**Comment by slavikdenis** [comment]
No worries, thanks anyways.

------

For anyone maybe wondering:
We have a client who needed app sharing through google play, but the app should not be released for open public. That's why we using closed track releases.

Now I need to force the users to have the latest release somehow. Because there is no public Google Play page for the app, it's impossible to use this library.

Anyways, if your app is using firebase, you can try what I will: https://medium.com/@sembozdemir/force-your-users-to-update-your-app-with-using-firebase-33f1e0bcec5a & https://rnfirebase.io/docs/v5.x.x/config/example
